version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
    image: ticket-api
    depends_on:
      - postgres
    command: sh -c "npm run start:dev"
    env_file: .env
    ports:
      - '10000:3000'
    networks:
      - ticket-network

  postgres:
    image: postgres:13
    container_name: ticket-pg-db
    ports:
      - '20000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ticket-network

  redis:
    container_name: ticket-redis
    image: redis:7.4-alpine
    restart: always
    ports:
      - '26379:6379'
    networks:
      - ticket-network

volumes:
  postgres-data:

networks:
  ticket-network:
