FROM node:20.18.0-alpine

WORKDIR /usr/app

# Install system dependencies
RUN apk add --no-cache git

# Copy package files
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy application code
COPY . .

# Build the application
RUN npm run build

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "dist/main"]
